//
// Generated file, do not edit! Created by opp_msgtool 6.0 from msg/PingMessage.msg.
//

#ifndef __PINGMESSAGE_M_H
#define __PINGMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class PingMessage;
/**
 * Class generated from <tt>msg/PingMessage.msg:1</tt> by opp_msgtool.
 * <pre>
 * message PingMessage
 * {
 *     string msg;
 * 
 * }
 * </pre>
 */
class PingMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string msg;

  private:
    void copy(const PingMessage& other);

  protected:
    bool operator==(const PingMessage&) = delete;

  public:
    PingMessage(const char *name=nullptr, short kind=0);
    PingMessage(const PingMessage& other);
    virtual ~PingMessage();
    PingMessage& operator=(const PingMessage& other);
    virtual PingMessage *dup() const override {return new PingMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getMsg() const;
    virtual void setMsg(const char * msg);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PingMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PingMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline PingMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<PingMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PINGMESSAGE_M_H

